apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name:  {{ .Values.env }}-spentonwow-frontend-ingress
  namespace: {{ .Values.env }}-spentonwow-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "lets-encrypt"
spec:
  tls:
    - hosts:
        - {{ if .Values.prod }}spentonwow.com{{ else }}{{ .Values.env }}.spentonwow.com{{ end }}
      secretName:  {{ .Values.env }}-wowspent-serving-cert-server-cert
  rules:
    - host: {{ if .Values.prod }}spentonwow.com{{ else }}{{ .Values.env }}.spentonwow.com{{ end }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ .Values.env }}-spentonwow-frontend
                port:
                  number: 443
