apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.env }}-spentonwow-frontend
  namespace:  {{ .Values.env }}-spentonwow-frontend
spec:
  selector:
    app:  {{ .Values.env }}-spentonwow-frontend
  ports:
    - protocol: TCP
      port: 443
      targetPort: 3000
